# -*- coding: utf-8 -*-
"""Lot 71 — contenu : nouveaux événements dans tous les pools.
Dépêches +36 (dont 3 extrêmes), rumeurs +16, anecdotes d'exécution +25, desk +12, exigences +10,
conseil +8, incidents +8, accidents de levier +6. Dépêches orientées vers les marchés les moins
cités (GBP, R, NRAM, KC, OAT, TOPX, BTC, EUA, BDI, MXP, NQ, HG) et vers le haut (les anciennes
penchaient du côté de la baisse des actions). Doublons thématiques écartés à la main contre les
titres existants. Aucune clé d'effet nouvelle."""
import sys; sys.path.insert(0,'patches')
from _lib import Ed
e=Ed()
NEW=r'''MACROEV.push(
 {t:"La Banque d'Angleterre relève ses taux de 75 points de base",who:"Londres · 12h00",p:"Le vote est unanime, le communiqué parle d'une inflation « enracinée ». Le sterling bondit, les gilts décrochent.",rum:"Un ancien membre du comité consulté par le desk trouve le ton des derniers discours étrangement martial.",hit:{GBP:1.6,R:-1.8,ESTX:-0.4}},
 {t:"Accord entre Londres et Bruxelles sur les services financiers",who:"Communiqué conjoint",p:"L'équivalence est accordée pour dix ans. Les banques de la City suspendent leurs déménagements.",hit:{GBP:1.3,ESTX:0.5,R:0.4}},
 {t:"La Bourse de Tokyo impose des plans de redressement aux sociétés décotées",who:"Bourse de Tokyo · directive",p:"Les sociétés cotées sous leur valeur comptable doivent publier un plan. Les rachats d'actions pleuvent.",hit:{TOPX:1.3,JPY:-0.3}},
 {t:"La France perd son double A",who:"Agence de notation · vendredi 22h00",p:"La dégradation tombe après la fermeture. Les gérants obligataires tenus par leurs mandats devront vendre lundi.",rum:"Un analyste souverain du desk trouve que l'agence a avancé la date de sa revue sans explication.",hit:{OAT:-1.9,ESTX:-0.6,EUR:-0.5,GBL:0.4}},
 {t:"Le gouvernement français survit à une motion de censure",who:"Assemblée nationale · 19h40",p:"Trois voix d'écart. L'écart entre l'OAT et le Bund se resserre de dix points de base en une heure.",hit:{OAT:1.3,ESTX:0.4,EUR:0.3}},
 {t:"La BCE active son instrument anti-fragmentation",who:"Francfort · conférence de presse",p:"Achats illimités de dettes souveraines « en cas de désordre injustifié ». La présidente ne dit pas quels pays.",hit:{OAT:1.5,ESTX:0.8,EUR:0.5,GBL:-0.5}},
 {t:"Récolte record de robusta au Vietnam",who:"Organisation internationale du café · rapport",p:"Les sacs arrivent en masse et les entrepôts de Rotterdam débordent.",hit:{KC:-2.0}},
 {t:"Le prix plancher du carbone européen est voté",who:"Parlement européen · vote final",p:"Un plancher de 60 € la tonne, relevé chaque année. Les industriels cessent de parier sur un effondrement.",hit:{EUA:2.0,ESTX:-0.2}},
 {t:"Bruxelles distribue des quotas gratuits supplémentaires",who:"Commission européenne",p:"Au nom de la compétitivité, l'industrie lourde reçoit une rallonge. L'offre excédentaire revient.",rum:"Un lobbyiste de l'acier se vante auprès du desk d'avoir obtenu « quelque chose de très concret ».",hit:{EUA:-2.2}},
 {t:"Le canal de Panama rouvre à plein régime",who:"Autorité du canal",p:"Les pluies sont revenues, les restrictions de tirant d'eau sont levées. Les files de vraquiers se résorbent.",hit:{BDI:-1.7,NRAM:0.5,ZW:-0.3}},
 {t:"Un laboratoire annonce un conducteur sans cuivre",who:"Revue scientifique · publication",p:"Un alliage d'aluminium, industrialisable en trois ans selon ses auteurs. Le marché y croit à moitié.",hit:{HG:-1.4,NQ:0.5}},
 {t:"Résultats géants d'un fabricant de puces",who:"Publication trimestrielle · 22h05",p:"Chiffre d'affaires doublé, prévisions relevées de moitié. Les cotations après-bourse s'emballent.",rum:"Les fournisseurs asiatiques du groupe commandent à nouveau des machines de gravure.",hit:{NQ:2.0,ES:0.8,TOPX:0.4,VX:-0.6}},
 {t:"Enquête antitrust contre quatre géants du numérique",who:"Département de la Justice",p:"Un démantèlement est évoqué pour la publicité et l'informatique dématérialisée. Les avocats parlent de dix ans.",hit:{NQ:-1.6,ES:-0.5}},
 {t:"Le Mexique signe un accord de relocalisation industrielle",who:"Mexico · annonce présidentielle",p:"Constructeurs automobiles et électroniciens américains déplacent leurs usines d'Asie vers le nord du pays.",hit:{MXP:1.6,MXEF:0.5,HG:0.3}},
 {t:"La banque centrale mexicaine baisse ses taux par surprise",who:"Banxico · 13h00",p:"Cent points de base d'un coup. Le portage fond, les capitaux rapides repartent.",hit:{MXP:-1.8}},
 {t:"La Réserve australienne relève ses taux contre toute attente",who:"Sydney · 14h30",p:"Le marché attendait une pause. Le gouverneur parle d'un immobilier « hors de contrôle ».",hit:{AUD:1.5,MXEF:-0.2}},
 {t:"Le bitcoin franchit son record historique",who:"Plateformes d'échange",p:"Les liquidations de positions courtes s'enchaînent. Les réseaux sociaux ne parlent que de ça.",hit:{BTC:2.0,NQ:0.3}},
 {t:"Inflation américaine sous les attentes pour le troisième mois",who:"Bureau des statistiques · 14h30",p:"Les loyers ralentissent enfin. Le marché anticipe une première baisse de taux.",hit:{TN:1.3,ES:0.9,NQ:1.1,GC:0.6,EUR:0.5,VX:-0.7}},
 {t:"Rebond surprise de l'activité européenne",who:"Indices des directeurs d'achat · 10h00",p:"L'industrie allemande repasse au-dessus de 50 pour la première fois en deux ans.",hit:{ESTX:1.3,EUR:0.7,GBL:-0.6,HG:0.4}},
 {t:"Le gouverneur de la Banque du Japon évoque des taux négatifs à nouveau",who:"Tokyo · audition parlementaire",p:"Une phrase glissée en fin de réponse. Les opérations de portage en yen reprennent dans l'heure.",hit:{JPY:-1.5,JGB:0.9,TOPX:0.7,MXP:0.5,AUD:0.4}},
 {t:"Le fret sec s'effondre avec la demande chinoise",who:"Baltic Exchange · séance",p:"Les affréteurs annulent leurs réservations de capesize. Des navires attendent au mouillage sans cargaison.",hit:{BDI:-2.1,HG:-0.6,AUD:-0.5}},
 {t:"Une maladie fongique ravage les caféiers d'Amérique centrale",who:"Institut agronomique · alerte",p:"La rouille orangée a gagné le Honduras et le Guatemala. Les coopératives craignent de perdre un tiers de la récolte.",rum:"Un agronome en contact avec le desk décrit des feuilles tachées dans des parcelles jusque-là épargnées.",hit:{KC:2.2}},
 {t:"Les navires doivent ralentir pour réduire leurs émissions",who:"Organisation maritime internationale",p:"Une vitesse maximale est imposée aux vraquiers. Il faut plus de navires pour transporter la même cargaison.",hit:{BDI:1.6,EUA:0.4,CL:-0.3}},
 {t:"Bruxelles autorise les crédits carbone internationaux",who:"Commission européenne · proposition",p:"Les industriels pourront compenser une partie de leurs émissions avec des projets à l'étranger, bien moins chers.",rum:"Un fonctionnaire européen parle au desk d'un « assouplissement pragmatique » en préparation.",hit:{EUA:-1.8}},
 {t:"Plan européen de rénovation des lignes électriques",who:"Commission européenne · annonce",p:"Des centaines de milliers de kilomètres de lignes à remplacer d'ici dix ans. Les câbliers doublent leurs carnets de commandes.",hit:{HG:1.4,EUA:0.6,ESTX:0.4}},
 {t:"Le Trésor britannique réduit ses émissions de gilts longs",who:"Bureau de gestion de la dette",p:"Le programme de l'année est raccourci, les maturités au-delà de vingt ans divisées par deux.",hit:{R:1.5,GBP:0.4}},
 {t:"Paris présente un budget en excédent primaire",who:"Bercy · conférence de presse",p:"Pour la première fois depuis vingt ans, les dépenses hors intérêts sont couvertes. Les agences de notation saluent l'effort.",hit:{OAT:1.4,ESTX:0.3}},
 {t:"Réforme judiciaire contestée au Mexique",who:"Congrès mexicain · vote",p:"Les juges seront désormais élus. Les investisseurs étrangers s'interrogent sur la protection des contrats.",rum:"Un avocat d'affaires de Mexico dit au desk que ses clients préparent des arbitrages internationaux.",hit:{MXP:-1.7,MXEF:-0.4}},
 {t:"Washington adopte un cadre légal pour les actifs numériques",who:"Congrès américain · vote final",p:"Statut clair, régulateur désigné, règles de garde. Les banques peuvent enfin proposer du bitcoin à leurs clients.",hit:{BTC:1.9,NQ:0.3}},
 {t:"Les marges des entreprises américaines atteignent un record",who:"Saison des résultats · synthèse",p:"Neuf entreprises sur dix battent les attentes. Les analystes relèvent leurs prévisions pour l'année suivante.",hit:{ES:1.3,NQ:1.2,VX:-0.6}},
 {t:"Les fonds de pension britanniques reviennent aux actions domestiques",who:"Association des fonds de pension",p:"Un accord avec le gouvernement : 5 % des actifs en actions britanniques d'ici trois ans. Les capitaux étrangers suivent.",hit:{GBP:0.9,R:-0.4}},
 {t:"Sécheresse hivernale en Europe du Sud",who:"Agence européenne de l'environnement",p:"Les réservoirs espagnols et italiens sont au tiers de leur capacité. Les barrages hydroélectriques tournent au ralenti.",hit:{NRAM:-1.6,EUA:0.8,ZW:0.5}},
 {t:"Un fonds activiste prend 10 % d'un conglomérat japonais",who:"Déclaration de franchissement de seuil",p:"Il réclame la vente de six filiales et un rachat d'actions massif. Les autres conglomérats bondissent par contagion.",hit:{TOPX:0.9,JPY:-0.2}},
 {x:1,t:"Pékin liquide ses bons du Trésor américain",who:"Fil d'actualité · 03h40",p:"Le ministère des finances chinois annonce la vente de l'intégralité de ses titres américains. Les adjudications suivantes n'ont plus d'acheteur naturel.",hit:{TN:-3.2,EUR:1.8,JPY:1.6,GC:2.8,ES:-2.2,NQ:-2.4,VX:2.4,MXEF:-1.8},liq:1.8},
 {x:1,t:"Collision géante : le détroit de Malacca est bloqué",who:"Autorité maritime de Singapour · 05h10",p:"Deux superpétroliers en feu au milieu du chenal. Une part énorme du commerce maritime mondial doit contourner l'Indonésie.",hit:{BDI:3.6,CL:2.6,MXEF:-2.0,TOPX:-1.6,AUD:-1.4,ES:-1.0,KC:1.2},liq:1.6},
 {x:1,t:"Rupture d'un grand barrage en Asie",who:"Fil d'actualité · 11h20",p:"Des millions de personnes évacuées, un bassin industriel sous les eaux, la moitié des usines de composants de la région à l'arrêt.",hit:{NRAM:3.0,MXEF:-2.6,HG:-1.8,NQ:-1.6,ZW:1.8,BDI:-1.4,GC:1.4},liq:1.6}
);
RUMORS.push(
 {src:"Transporteur routier",t:"Les commandes de camions de fret reculent pour le deuxième mois",v:[-2,0,0,-1],rel:'moyenne'},
 {src:"Données de cartes bancaires",t:"Les dépenses des ménages en restauration accélèrent nettement",v:[2,1,0,1],rel:'forte'},
 {src:"Économiste maison",t:"Les anticipations d'inflation des ménages décrochent de leur plus haut",v:[0,-2,0,1],rel:'moyenne'},
 {src:"Courtier matières premières",t:"Les primes physiques sur le cuivre s'envolent à Shanghai",v:[2,1,-1,1],rel:'moyenne'},
 {src:"Bruit de salle",t:"Une banque centrale asiatique vendrait ses réserves en dollars",v:[0,0,-2,0],rel:'faible'},
 {src:"Trader de nuit",t:"Les exportateurs japonais vendent des dollars à chaque rebond",v:[0,0,-1,-1],rel:'faible'},
 {src:"Syndicat patronal",t:"Les négociations salariales de branche se concluent au-dessus de 5 %",v:[1,2,0,0],rel:'forte'},
 {src:"Données satellites",t:"Les panaches des cheminées d'usines chinoises s'épaississent",v:[2,1,-1,1],rel:'moyenne'},
 {src:"Banquier d'affaires",t:"Les lignes de crédit aux fonds à levier sont réduites discrètement",v:[-1,0,1,-2],rel:'moyenne'},
 {src:"Broker taux",t:"Les assureurs vie achètent de la duration longue comme jamais",v:[-1,-1,0,0],rel:'moyenne'},
 {src:"Ancien de la banque centrale",t:"Le comité tolérerait une inflation au-dessus de la cible pendant deux ans",v:[1,2,-1,1],rel:'faible'},
 {src:"Bruit de salle",t:"Un fonds activiste accumule des positions sur les banques européennes",v:[1,0,-1,1],rel:'faible'},
 {src:"Agence immobilière",t:"Les ventes de logements neufs s'effondrent dans les grandes métropoles",v:[-2,-1,0,-1],rel:'moyenne'},
 {src:"Courtier fret",t:"Les armateurs repoussent leurs commandes de navires neufs",v:[-1,0,1,-1],rel:'moyenne'},
 {src:"Économiste maison",t:"Le crédit aux entreprises repart dans la zone euro",v:[1,1,-1,1],rel:'forte'},
 {src:"Desk options",t:"Les achats de protection contre une baisse des actions reculent fortement",v:[1,0,0,2],rel:'faible'}
);
TRADER_EXEC.push(
 {who:"Ingrid Bergström · taux",t:"« Le gilt a une adjudication à 11 heures. Je passe après »",need:['R'],p:"« Le Trésor britannique place une ligne longue. Si l'adjudication se passe mal, on achète moins cher. Si elle se passe bien, on paie la hausse. »",
  ch:[{b:"Attendre l'adjudication",s:"Coûts sur le gilt −25 %. 35 % de risque que le marché parte : −0,25 %.",e:{tcMultOn:['R'],tcMult:0.75,risk:[0.35,-0.0025],riskMsg:"L'adjudication a été couverte trois fois, le gilt est parti",safeTxt:"L'adjudication a déçu : vous achetez au creux."}},
      {b:"Exécuter avant, tout de suite",s:"Plein tarif.",e:{}}]},
 {who:"Ingrid Bergström · taux",t:"« L'OAT se traite mieux par un panier de base »",need:['OAT'],p:"« Les teneurs de marché français sont frileux cette semaine. Je peux passer par le contrat et ajuster avec le cash, mais on garde un peu de base. »",
  ch:[{b:"Passer par le contrat et ajuster",s:"Coûts sur l'OAT −30 %, 30 % de risque de base : −0,2 %.",e:{tcMultOn:['OAT'],tcMult:0.7,risk:[0.3,-0.002],riskMsg:"La base contrat-comptant s'est écartée"}},
      {b:"Traiter en direct avec les teneurs",s:"Plein tarif.",e:{}}]},
 {who:"Ingrid Bergström · taux",t:"« Le Trésor américain rachète ses anciens titres cette semaine »",need:['TN'],p:"« Des rachats pour lisser la courbe. Pendant trois jours, il y a un acheteur qui ne regarde pas le prix. »",
  ch:[{b:"Exécuter pendant les rachats",s:"Coûts sur le T-Note −30 %.",e:{tcMultOn:['TN'],tcMult:0.7}},
      {b:"Exécuter aujourd'hui",s:"Plein tarif.",e:{}}]},
 {who:"Bartolomeo « Tuco » Ossobuco · énergie",t:"« Le roulement de la fin de mois est bondé. Je roule une semaine avant »",need:['CL'],p:"« Tout le monde roule le même jour, les indices, les ETF, les banques. Une semaine plus tôt, le calendrier est vide. Mais la courbe peut bouger. »",
  ch:[{b:"Rouler une semaine avant",s:"Coûts sur le pétrole −35 %, 30 % de risque de courbe : −0,3 %.",e:{tcMultOn:['CL'],tcMult:0.65,risk:[0.3,-0.003],riskMsg:"La courbe du brut s'est déformée pendant la semaine"}},
      {b:"Rouler avec tout le monde",s:"Plein tarif.",e:{}}]},
 {who:"Bartolomeo « Tuco » Ossobuco · énergie",t:"« Un raffineur veut me vendre un bloc de brut hors marché »",need:['CL'],p:"« Il a besoin de liquidités avant sa clôture comptable. Il me fait un prix. Le genre de prix qui fait réfléchir. »",
  ch:[{b:"Prendre le bloc",s:"Coûts sur le pétrole −45 %, comité −3, 25 % de risque qu'il sache quelque chose : −0,4 %.",e:{tcMultOn:['CL'],tcMult:0.55,rc:-3,risk:[0.25,-0.004],riskMsg:"Le raffineur savait : le brut a décroché le lendemain"}},
      {b:"Prendre la moitié",s:"Coûts −20 %, 12 % de risque : −0,2 %.",e:{tcMultOn:['CL'],tcMult:0.8,risk:[0.12,-0.002],riskMsg:"Le raffineur savait quelque chose"}},
      {b:"Passer sur le marché",s:"Plein tarif.",e:{}}]},
 {who:"Bartolomeo « Tuco » Ossobuco · énergie",t:"« Le café, je le traite par téléphone, pas à l'écran »",need:['KC'],p:"« Le carnet affiché ne vaut rien. Les vraies quantités sont chez trois négociants à Genève. Je les connais. Enfin, deux sur trois. »",
  ch:[{b:"Traiter par téléphone",s:"Coûts sur le café −40 %, 20 % de risque de mauvaise contrepartie : −0,3 %.",e:{tcMultOn:['KC'],tcMult:0.6,risk:[0.2,-0.003],riskMsg:"Le troisième négociant a publié votre ordre dans la minute"}},
      {b:"Rester à l'écran",s:"Plein tarif.",e:{}}]},
 {who:"Boris Rasoumovsky · devises",t:"« La banque centrale suisse achète des euros, je le sens »",need:['EUR'],p:"« Quelqu'un achète des euros par paquets identiques depuis ce matin. Si c'est bien elle, on se met dans son sillage. Si c'est quelqu'un qui l'imite, on se fait piéger. »",
  ch:[{b:"Suivre l'acheteur",s:"Coûts sur l'euro −35 %, 30 % de risque que ce ne soit pas elle : −0,25 %.",e:{tcMultOn:['EUR'],tcMult:0.65,risk:[0.3,-0.0025],riskMsg:"Ce n'était pas la banque centrale, l'imitateur a tout revendu"}},
      {b:"Traiter normalement",s:"Plein tarif.",e:{}}]},
 {who:"Boris Rasoumovsky · devises",t:"« Le peso ne se traite qu'à Mexico. Je me lève à trois heures »",need:['MXP'],p:"« Pendant la séance de Mexico, la fourchette est divisée par deux. Mais je serai seul et fatigué. »",
  ch:[{b:"Laisser Boris traiter de nuit",s:"Coûts sur le peso −40 %, 20 % de risque d'erreur de fatigue : −0,25 %.",e:{tcMultOn:['MXP'],tcMult:0.6,risk:[0.2,-0.0025],riskMsg:"Boris a tapé un zéro de trop, rattrapé à moitié"}},
      {b:"Traiter pendant Londres",s:"Plein tarif, Boris dort.",e:{}}]},
 {who:"Boris Rasoumovsky · devises",t:"« Le sterling, je le passe contre l'euro, pas contre le dollar »",need:['GBP'],p:"« Le croisé est plus liquide aujourd'hui. On récupère la jambe en dollar ensuite, en deux temps. »",
  ch:[{b:"Passer par le croisé",s:"Coûts sur le sterling −25 %, 30 % de risque sur la deuxième jambe : −0,15 %.",e:{tcMultOn:['GBP'],tcMult:0.75,risk:[0.3,-0.0015],riskMsg:"Le dollar a bougé entre les deux jambes"}},
      {b:"Traiter en direct contre le dollar",s:"Plein tarif.",e:{}}]},
 {who:"Wing-Fat « Winnie » Leung · Asie",t:"« Les places asiatiques ferment pour le Nouvel An lunaire »",need:['MXEF'],p:"« Une semaine sans Shanghai, Hong Kong ni Taipei. Soit on passe tout avant, soit on attend la réouverture, avec ce qui se sera passé entre-temps. »",
  ch:[{b:"Tout passer avant la fermeture",s:"Coûts sur les émergents +15 %, aucun risque.",e:{tcMultOn:['MXEF'],tcMult:1.15}},
      {b:"Attendre la réouverture",s:"Coûts −20 %, 35 % de risque d'écart à la réouverture : −0,3 %.",e:{tcMultOn:['MXEF'],tcMult:0.8,risk:[0.35,-0.003],riskMsg:"Les places ont rouvert en écart"}}]},
 {who:"Wing-Fat « Winnie » Leung · Asie",t:"« Mon cousin à Hong Kong a une contrepartie pour les émergents »",need:['MXEF'],p:"« Un bloc, négocié en privé, réglé demain. Mon cousin est très sérieux. Il a juste changé trois fois de société cette année. »",
  ch:[{b:"Faire confiance au cousin",s:"Coûts sur les émergents −45 %, comité −4, 20 % de risque de règlement raté : −0,35 %.",e:{tcMultOn:['MXEF'],tcMult:0.55,rc:-4,risk:[0.2,-0.0035],riskMsg:"Le règlement a échoué, rachat en urgence"}},
      {b:"Passer par le marché",s:"Plein tarif.",e:{}}]},
 {who:"Dwight Tannenbaum · exécution quantitative",t:"« Mon nouvel algorithme suit le volume en temps réel »",p:"« Il participe à 8 % du volume, pas plus. Il n'a tourné qu'en simulation. Les résultats sont superbes. En simulation. »",
  ch:[{b:"Le mettre en production",s:"Coûts −25 % sur tout le trimestre, 25 % de risque de bogue : −0,3 %.",e:{tcMult:0.75,risk:[0.25,-0.003],riskMsg:"L'algorithme a confondu volume et volatilité"}},
      {b:"Le tester sur un seul marché",s:"Coûts −8 %.",e:{tcMult:0.92}},
      {b:"Garder l'ancien",s:"Plein tarif.",e:{}}]},
 {who:"Dwight Tannenbaum · exécution quantitative",t:"« Je peux cacher nos ordres dans les ordres des autres »",p:"« Des ordres à cours limité au milieu de la fourchette, renouvelés toutes les cent millisecondes. Personne ne nous voit. Sauf ceux qui regardent. »",
  ch:[{b:"Ordres invisibles",s:"Coûts −20 %, 25 % de risque d'être détecté : −0,15 %.",e:{tcMult:0.8,risk:[0.25,-0.0015],riskMsg:"Un teneur de marché a reconnu le motif"}},
      {b:"Exécution standard",s:"Plein tarif.",e:{}}]},
 {who:"Jean-Kevin Lévêque-Charbonnier · junior",t:"« J'ai lu un article sur le trading haute fréquence »",p:"« On pourrait placer nos ordres une microseconde avant les autres. Il suffit d'un câble plus court. J'ai déjà appelé l'installateur. »",
  ch:[{b:"Annuler l'installateur",s:"Plein tarif, Jean-Kevin est déçu.",e:{}},
      {b:"Le laisser essayer",s:"−5 pb de câble, coûts −5 %.",e:{cash:-0.0005,tcMult:0.95}}]},
 {who:"Jean-Kevin Lévêque-Charbonnier · junior",t:"« J'ai passé les ordres hier soir, pour gagner du temps »",p:"« Vous aviez dit que vous alliez sûrement acheter, alors j'ai pris de l'avance. Au prix d'hier soir. Qui était plus bas. Je crois. »",
  ch:[{b:"Garder ce qu'il a fait",s:"Coûts −15 %, comité −4, 50 % que le prix d'hier soit meilleur : +0,2 %, sinon −0,2 %.",e:{tcMult:0.85,rc:-4,risk:[0.5,0.002],riskMsg:"Le prix d'hier soir était meilleur",safeTxt:"Le prix d'hier soir était pire : −0,20 %.",safePnl:-0.002}},
      {b:"Tout déboucler et recommencer",s:"Coûts +20 %, comité +2.",e:{tcMult:1.2,rc:2}}]},
 {who:"Mireille Cauchemar · contrôle des risques",t:"« Le courtier que vous utilisez n'a plus de notation »",p:"« Il a été dégradé hier soir. Je ne dis pas qu'il va faire défaut. Je dis que je ne dormirai pas tant que vos marges seront chez lui. »",
  ch:[{b:"Transférer chez un autre courtier",s:"Coûts +15 %, comité +4.",e:{tcMult:1.15,rc:4}},
      {b:"Rester, il est moins cher",s:"Comité −5, 5 % de risque de gel des marges : −0,8 %.",e:{rc:-5,risk:[0.05,-0.008],riskMsg:"Le courtier a gelé les comptes clients"}}]},
 {who:"Mireille Cauchemar · contrôle des risques",t:"« Vos ordres dépassent 10 % du volume quotidien sur trois marchés »",p:"« Au-delà, vous êtes le marché. Et quand on est le marché, on ne sort pas. »",
  ch:[{b:"Alléger la plus grosse position",s:"Le plus gros contributeur au risque perd une unité, comité +4.",e:{cutTop1:true,rc:4}},
      {b:"Étaler sur trois jours",s:"Coûts −10 %, 30 % de risque de glissement : −0,2 %.",e:{tcMult:0.9,risk:[0.3,-0.002],riskMsg:"Le marché a glissé pendant l'étalement"}},
      {b:"Passer quand même",s:"Comité −4.",e:{rc:-4}}]},
 {who:"Le desk, unanime",t:"« Le marché est fermé demain aux États-Unis. On passe tout aujourd'hui ? »",p:"« Jour férié à New York. Liquidité en berne à partir de 18 heures, et demain il n'y a que Londres. »",
  ch:[{b:"Tout passer avant 18 heures",s:"Coûts +10 %, aucun risque.",e:{tcMult:1.1}},
      {b:"Profiter du creux pour traiter en douceur",s:"Coûts −15 %, 25 % de risque de nouvelle pendant le férié : −0,3 %.",e:{tcMult:0.85,risk:[0.25,-0.003],riskMsg:"Une nouvelle est tombée pendant le jour férié"}}]},
 {who:"Le desk, unanime",t:"« On a un stagiaire qui code très bien. Il propose d'automatiser les roulements »",p:"« Un script, deux cents lignes, relu par personne. Il dit que ça marche. »",
  ch:[{b:"Faire relire le script",s:"−3 pb de temps de relecture, coûts −10 %.",e:{cash:-0.0003,tcMult:0.9}},
      {b:"Le lancer tel quel",s:"Coûts −15 %, 15 % de risque de roulement raté : −0,4 %.",e:{tcMult:0.85,risk:[0.15,-0.004],riskMsg:"Le script a roulé les contrats deux fois"}},
      {b:"Continuer à la main",s:"Plein tarif.",e:{}}]},
 {who:"Le desk, unanime",t:"« Il y a une panne de l'écran principal. On passe par le téléphone ? »",p:"« La plateforme de la bourse rame depuis l'ouverture. Les courtiers vocaux prennent les ordres, à leur tarif. »",
  ch:[{b:"Passer par les courtiers vocaux",s:"Coûts +20 %, aucune attente.",e:{tcMult:1.2}},
      {b:"Attendre le retour de la plateforme",s:"Coûts inchangés, 35 % de risque que le marché parte entre-temps : −0,25 %.",e:{risk:[0.35,-0.0025],riskMsg:"La plateforme est revenue, le marché aussi, mais plus haut"}}]},
 {who:"Le prime broker",t:"« Nous proposons de compenser vos positions en interne »",p:"« Nous avons des clients en face de vous sur une bonne partie du book. On croise en interne, sans passer par le marché. Discrétion garantie. »",
  ch:[{b:"Accepter le croisement interne",s:"Coûts −30 %, comité −3, 20 % de risque que les positions circulent.",e:{tcMult:0.7,rc:-3,risk:[0.2,-0.0015],riskMsg:"Vos positions ont circulé chez le prime broker"}},
      {b:"Refuser",s:"Plein tarif.",e:{}}]},
 {who:"Le courtier de Chicago",t:"« Je vous passe le blé en ordre lié avec le maïs »",need:['ZW'],p:"« L'écart blé-maïs est très liquide. Je vous fais l'écart, puis je solde le maïs. Deux étapes, deux risques, un bon prix. »",
  ch:[{b:"Passer par l'écart",s:"Coûts sur le blé −35 %, 30 % de risque sur la deuxième jambe : −0,25 %.",e:{tcMultOn:['ZW'],tcMult:0.65,risk:[0.3,-0.0025],riskMsg:"Le maïs a bougé avant la deuxième jambe"}},
      {b:"Traiter le blé seul",s:"Plein tarif.",e:{}}]},
 {who:"Le courtier de Chicago",t:"« Un minier couvre sa production de l'an prochain. Je vous mets en face »",need:['HG'],p:"« Un bloc énorme, vendu d'un coup, à un prix négocié. Si vous êtes acheteur, c'est votre jour. Si vous êtes vendeur, attendez demain. »",
  ch:[{b:"Se mettre en face du bloc",s:"Coûts sur le cuivre −40 %, 25 % de risque d'être du mauvais côté : −0,3 %.",e:{tcMultOn:['HG'],tcMult:0.6,risk:[0.25,-0.003],riskMsg:"Vous étiez du même côté que le minier"}},
      {b:"Rester à l'écart",s:"Plein tarif.",e:{}}]},
 {who:"Un vendeur de données",t:"« Notre flux de carnets d'ordres consolidé est en promotion »",p:"« Toutes les places, en temps réel, avec l'historique. Vos traders verront enfin où est la liquidité. »",
  ch:[{b:"Acheter l'abonnement",s:"−15 pb, coûts −15 %.",e:{cash:-0.0015,tcMult:0.85}},
      {b:"Refuser",s:"Plein tarif.",e:{}}]},
 {who:"Sœur Marie-Alpha · exécution systématique",t:"« Le modèle veut exécuter en fonction de la volatilité intrajournalière »",p:"« Quand la volatilité baisse, il accélère. Quand elle monte, il attend. C'est écrit depuis longtemps. Personne ne l'avait activé. »",
  ch:[{b:"Activer la règle",s:"Coûts −20 %, 20 % de risque que le marché file pendant l'attente : −0,25 %.",e:{tcMult:0.8,risk:[0.2,-0.0025],riskMsg:"La volatilité est restée haute et le marché a filé"}},
      {b:"Exécution uniforme",s:"Plein tarif.",e:{}}]}
);
TRADER_MID.push(
 {who:"Ingrid Bergström · taux",t:"« Le gilt est trop bas. Les fonds de pension vont racheter »",p:"« Ils ont vendu pour payer leurs appels de marge. Maintenant qu'ils ont du collatéral, ils rachètent. Je veux être devant. »",
  ch:[{b:"Une unité longue sur le gilt",s:"R +1. 55 % de +0,4 %, sinon −0,35 %.",e:{kAddAbs:['R',1],gamble2:[0.55,0.004,-0.0035]}},{b:"Refuser",s:"Ingrid note la date dans son carnet.",e:{}}]},
 {who:"Bartolomeo « Tuco » Ossobuco · énergie",t:"« Un pétrolier est bloqué au large de Rotterdam. Je vends le brut »",p:"« Il transporte deux millions de barils que personne ne veut décharger. Le marché physique est saturé, le papier ne l'a pas encore vu. »",
  ch:[{b:"Une unité courte sur le pétrole",s:"CL −1. 50 % de +0,5 %, sinon −0,45 %.",e:{kAddAbs:['CL',-1],gamble2:[0.5,0.005,-0.0045]}},{b:"Laisser Tuco regarder les navires",s:"« Vous regretterez. »",e:{}}]},
 {who:"Boris Rasoumovsky · devises",t:"« L'Australie publie ses chiffres cette nuit. Je joue le dollar australien »",p:"« Emploi, balance commerciale, minerai. Tout est bon, le marché ne l'a pas encore compris. Enfin, je crois. »",
  ch:[{b:"Une unité longue sur l'AUD",s:"AUD +1. 50 % de +0,4 %, sinon −0,4 %.",e:{kAddAbs:['AUD',1],gamble2:[0.5,0.004,-0.004]}},{b:"Refuser",s:"Boris boude jusqu'au déjeuner.",e:{}}]},
 {who:"Wing-Fat « Winnie » Leung · Asie",t:"« Les exportateurs japonais n'ont jamais été aussi bon marché »",p:"« Le yen est faible, les marges records, et personne ne les achète. Je veux une unité de TOPIX, contre le Nasdaq. »",
  ch:[{b:"TOPIX long contre Nasdaq court",s:"TOPX +1, NQ −1. 55 % de +0,5 %, sinon −0,4 %.",e:{kAddAbs:['TOPX',1],kAddAbs2:['NQ',-1],gamble2:[0.55,0.005,-0.004]}},{b:"TOPIX seul",s:"TOPX +1. 50 % de ±0,4 %.",e:{kAddAbs:['TOPX',1],gamble2:[0.5,0.004,-0.004]}},{b:"Refuser",s:"Winnie range ses graphiques.",e:{}}]},
 {who:"Jean-Kevin Lévêque-Charbonnier · junior",t:"« J'ai trouvé une corrélation incroyable entre le café et le bitcoin »",p:"« Sur les six dernières semaines, elle est de 0,94. Je peux vous montrer le graphique. Il est en couleurs. »",
  ch:[{b:"Lui expliquer ce qu'est une corrélation fallacieuse",s:"Comité +1. Jean-Kevin apprend quelque chose.",e:{rc:1}},{b:"Le laisser jouer une unité de café",s:"KC +1. 45 % de +0,4 %, sinon −0,5 %.",e:{kAddAbs:['KC',1],gamble2:[0.45,0.004,-0.005]}},{b:"Ignorer",s:"Il envoie le graphique à tout le monde.",e:{}}]},
 {who:"Dwight Tannenbaum · exécution quantitative",t:"« Les signaux de tendance sont alignés sur quatre marchés »",p:"« Rarement vu. Je propose d'ajouter une unité dans le sens de la tendance sur les deux plus forts. »",
  ch:[{b:"Ajouter sur les deux tendances les plus fortes",s:"Deux unités dans le sens de la tendance, comité −1.",e:{trendAdd:2,rc:-1}},{b:"Une seule",s:"Une unité sur la tendance la plus forte.",e:{trendAdd:1}},{b:"Ne rien toucher",s:"Dwight archive son alerte.",e:{}}]},
 {who:"Mireille Cauchemar · contrôle des risques",t:"« Votre valeur à risque a doublé depuis le début du trimestre »",p:"« Je ne vous demande rien. Je vous préviens. La prochaine fois, je vous demanderai. »",
  ch:[{b:"Couper les deux plus gros contributeurs",s:"Deux positions perdent une unité, comité +5.",e:{cutTop2:true,rc:5}},{b:"Remercier et ne rien faire",s:"Comité −3.",e:{rc:-3}}]},
 {who:"Le desk, hilare",t:"« Jean-Kevin a été interviewé par une chaîne financière »",p:"« Il a dit que le fonds était « très long sur tout ce qui monte ». La séquence tourne en boucle sur les réseaux. »",
  ch:[{b:"Faire publier un démenti",s:"Investisseurs +1, comité +1, −2 pb d'avocats.",e:{cash:-0.0002,lp:1,rc:1}},{b:"En rire publiquement",s:"Investisseurs +3, comité −2.",e:{lp:3,rc:-2}},{b:"Ne rien dire",s:"Investisseurs −2.",e:{lp:-2}}]},
 {who:"Un économiste de renom",t:"« Je peux vous présenter au ministre des finances »",p:"« Un dîner privé, dix convives, aucune question interdite. Mes honoraires sont à la hauteur de l'occasion. »",
  ch:[{b:"Payer le dîner",s:"−8 pb. 50 % de repartir avec une vraie lecture : +0,5 %, sinon rien.",e:{cash:-0.0008,risk:[0.5,0.005],riskMsg:"Le ministre a parlé plus qu'il n'aurait dû",safeTxt:"Le ministre a parlé de football toute la soirée."}},{b:"Décliner",s:"Rien ne change.",e:{}}]},
 {who:"La conformité",t:"« Deux traders échangent sur une messagerie non archivée »",p:"« Rien d'illégal dans les messages, pour ce qu'on en a vu. Mais le régulateur n'aime pas ne pas voir. »",
  ch:[{b:"Déclarer spontanément au régulateur",s:"−5 pb d'amende, comité +4.",e:{cash:-0.0005,rc:4}},{b:"Rappel à l'ordre interne",s:"Comité −1, 12 % de contrôle : −0,5 %.",e:{rc:-1,risk:[0.12,-0.005],riskMsg:"Le régulateur l'a découvert lors d'un contrôle",riskRc:-6}},{b:"Ignorer",s:"Comité −4, 25 % de contrôle : −0,7 %.",e:{rc:-4,risk:[0.25,-0.007],riskMsg:"Le régulateur a saisi les téléphones",riskRc:-8}}]},
 {who:"Un chasseur de têtes",t:"Un concurrent tourne autour de Boris",p:"Trois déjeuners en deux semaines, toujours dans le même restaurant, toujours avec la même personne.",
  ch:[{b:"Lui offrir une prime de fidélité",s:"−4 pb, investisseurs +1.",e:{cash:-0.0004,lp:1}},{b:"Le laisser déjeuner",s:"Risque de débauchage accru.",e:{poach:0.15}},{b:"Lui confier plus de risque",s:"Il reste, comité −3.",e:{rc:-3}}]},
 {who:"Relations investisseurs",t:"« Un allocataire veut visiter la salle de marché demain »",p:"« Il veut voir les écrans, parler aux traders, et comprendre la dernière perte. En une heure. »",
  ch:[{b:"Organiser la visite complète",s:"−2 pb de préparation, investisseurs +4, comité −1.",e:{cash:-0.0002,lp:4,rc:-1}},{b:"Une visio de vingt minutes",s:"Investisseurs +1.",e:{lp:1}},{b:"Reporter",s:"Investisseurs −3.",e:{lp:-3}}]}
);
STAKE.push(
 {who:"Comité des risques",t:"« Votre exposition à l'inflation est unilatérale. Réduisez-la d'un tiers »",cond:()=>Math.abs(factorExpo(weights(S.k))[1])>0.05,p:"Le comité a relu le procès-verbal de la dernière banque centrale. Il n'a pas aimé ce qu'il a lu.",
  ch:[{b:"Obéir",s:"Exposition inflation réduite d'un tiers, comité +4.",e:{cutFactor:[1,0.33],rc:4}},{b:"Proposer une couverture partielle",s:"Comité +1, investisseurs −1.",e:{rc:1,lp:-1}},{b:"Refuser",s:"Comité −6.",e:{rc:-6}}]},
 {who:"Comité des risques",t:"« Le book dépend trop de l'appétit pour le risque »",cond:()=>Math.abs(factorExpo(weights(S.k))[3])>0.06,p:"Un seul facteur explique l'essentiel de votre risque. Le comité appelle ça un pari, pas un portefeuille.",
  ch:[{b:"Réduire cette exposition de moitié",s:"Exposition appétit coupée de moitié, comité +5.",e:{cutFactor:[3,0.5],rc:5}},{b:"Réduire d'un quart",s:"Comité +1.",e:{cutFactor:[3,0.25],rc:1}},{b:"Défendre la thèse",s:"Comité −5, investisseurs +1.",e:{rc:-5,lp:1}}]},
 {who:"Comité des risques · Mireille Cauchemar",t:"« Le bitcoin sort du périmètre autorisé »",cond:()=>IDX.BTC!==undefined&&S.k[IDX.BTC]!==0,p:"« Le dépositaire ne veut plus garder de contrats sur actifs numériques. Ce n'est pas moi, c'est lui. »",
  ch:[{b:"Fermer la position",s:"Bitcoin à zéro, comité +3.",e:{zeroOn:['BTC'],rc:3}},{b:"La réduire de moitié",s:"Comité −1.",e:{halfOn:['BTC'],rc:-1}},{b:"Changer de dépositaire",s:"−6 pb, comité −3.",e:{cash:-0.0006,rc:-3}}]},
 {who:"Comité des risques",t:"« Votre position sur le café dépasse ce que le marché peut absorber »",cond:()=>IDX.KC!==undefined&&Math.abs(S.k[IDX.KC])>=2,p:"Le café est un marché étroit. Le comité a calculé combien de jours il vous faudrait pour sortir. Le chiffre l'a inquiété.",
  ch:[{b:"Diviser la position par deux",s:"Café réduit de moitié, comité +4.",e:{halfOn:['KC'],rc:4}},{b:"Garder",s:"Comité −5.",e:{rc:-5}}]},
 {who:"Investisseur · caisse de retraite canadienne",t:"« Nous voulons une lettre trimestrielle plus détaillée »",p:"Position par position, avec la justification de chaque changement. Ils paient bien, ils demandent beaucoup.",
  ch:[{b:"Accepter",s:"Investisseurs +4, comité −1.",e:{lp:4,rc:-1}},{b:"Proposer une lettre factorielle",s:"Investisseurs +1.",e:{lp:1}},{b:"Refuser",s:"Investisseurs −4.",e:{lp:-4}}]},
 {who:"Investisseur · fonds souverain",t:"« Nous retirons 5 % pour rééquilibrer notre allocation »",p:"Rien de personnel, disent-ils. Leur portefeuille d'actions a trop monté, il faut vendre ailleurs.",
  ch:[{b:"Accepter sans discuter",s:"Retrait de 5 % de l'encours, investisseurs +2.",e:{flowOut:0.05,lp:2}},{b:"Négocier un étalement",s:"Retrait de 2 %, investisseurs −1.",e:{flowOut:0.02,lp:-1}}]},
 {who:"Investisseur · family office",t:"« Mon fils veut investir chez vous. Il a des idées »",p:"Le fils a vingt-six ans, une souscription de 3 % et des opinions très arrêtées sur le bitcoin.",
  ch:[{b:"Accepter la souscription",s:"Souscription de 3 %, passif plus nerveux, investisseurs +1.",e:{flowIn:0.03,flighty:true,lp:1}},{b:"Accepter, sans les idées",s:"Souscription de 2 %, investisseurs −1.",e:{flowIn:0.02,lp:-1}},{b:"Décliner poliment",s:"Investisseurs −2.",e:{lp:-2}}]},
 {who:"Consultant · Marchand & Fils",t:"« Votre dispositif de continuité d'activité n'a jamais été testé »",p:"Le consultant propose une simulation de panne complète un vendredi. Facturée, bien sûr.",
  ch:[{b:"Faire le test",s:"−4 pb, comité +4.",e:{cash:-0.0004,rc:4}},{b:"Un test sur table",s:"−1 pb, comité +1.",e:{cash:-0.0001,rc:1}},{b:"Reporter",s:"Comité −3.",e:{rc:-3}}]},
 {who:"Conseil d'administration",t:"« Le président veut comprendre la dernière perte »",p:"Il a lu un article sur « le fonds qui a mal lu la banque centrale ». Il n'est pas certain que ce soit vous. Il voudrait être certain que ce ne soit pas vous.",
  ch:[{b:"Préparer une note détaillée",s:"Comité +3, investisseurs +1.",e:{rc:3,lp:1}},{b:"L'appeler directement",s:"Investisseurs +2, comité −1.",e:{lp:2,rc:-1}},{b:"Laisser les relations investisseurs répondre",s:"Comité −2.",e:{rc:-2}}]},
 {who:"Investisseur · assureur",t:"« Nous voulons un plafond de perte sur le trimestre »",p:"Un seuil au-delà duquel vous coupez tout, écrit noir sur blanc. Leur actuaire en a besoin pour son modèle.",
  ch:[{b:"Accepter un stop sur le trimestre",s:"Le book sera coupé de moitié si le trimestre passe −8 % brut. Investisseurs +3.",e:{stopQ:true,lp:3}},{b:"Refuser",s:"Investisseurs −3.",e:{lp:-3}}]}
);
BOARDEV.push(
 {who:"Relations investisseurs",t:"Un fonds de dotation demande un traitement de faveur",
  p:"Il souscrirait 6 % de votre encours contre une réduction de la commission de performance et un droit de regard sur les positions.",
  ch:[{b:"Accepter",s:"L'encours grimpe, le comité n'aime pas les passe-droits.",e:{aum:0.06,lp:2,rc:-5}},
      {b:"Refuser les conditions",s:"Les autres investisseurs apprécient l'égalité de traitement.",e:{lp:1,rc:2}}]},
 {who:"Conformité",t:"Le régulateur annonce une inspection sur place",
  p:"Deux inspecteurs, trois semaines, un accès complet aux enregistrements. La date est fixée, pas la liste des questions.",
  ch:[{b:"Engager un cabinet pour préparer l'inspection",s:"Une facture immédiate, un rapport propre.",e:{cash:-0.002,rc:5}},
      {b:"Préparer en interne",s:"Moins cher, mais quelques zones d'ombre.",e:{rc:-3}}]},
 {who:"Salle de marché",t:"La salle réclame un nouveau système de gestion des ordres",
  p:"L'ancien date de huit ans et plante une fois par mois. Le nouveau coûte cher et demande trois mois de migration.",
  ch:[{b:"Financer le nouveau système",s:"Une facture immédiate, un comité rassuré.",e:{cash:-0.002,rc:4,lp:1}},
      {b:"Garder l'ancien",s:"La salle râle, le comité s'inquiète.",e:{rc:-3,lp:-1}}]},
 {who:"Presse",t:"Une agence de presse publie votre classement",
  p:"Vous êtes dans le premier quart sur trois ans, dans le dernier quart sur six mois. L'article choisit le second chiffre pour son titre.",
  ch:[{b:"Demander un rectificatif",s:"L'agence corrige, sans enthousiasme.",e:{lp:2,rc:-1}},
      {b:"Laisser passer",s:"Quelques allocataires appellent.",e:{lp:-3}}]},
 {who:"Prime broker",t:"Votre prime broker propose de doubler vos lignes de levier",
  p:"À conditions inchangées, pour « accompagner votre croissance ». L'offre expire à la fin de la semaine.",
  ch:[{b:"Accepter la ligne",s:"Le comité voit une tentation, les investisseurs une marque de confiance.",e:{lp:3,rc:-6}},
      {b:"Décliner",s:"Rien ne change.",e:{rc:2}}]},
 {who:"Relations investisseurs",t:"Un grand allocataire menace de partir",
  p:"Il représente 8 % de l'encours. Il veut une remise sur la commission de gestion, faute de quoi il rachète au prochain trimestre.",
  ch:[{b:"Céder une remise",s:"Il reste. La remise pèse sur le fonds.",e:{cash:-0.002,lp:3}},
      {b:"Le laisser partir",s:"Rachat de 8 % de l'encours.",e:{aum:-0.08,lp:-2,rc:2}}]},
 {who:"Comité des risques",t:"Le comité veut un deuxième signataire sur chaque ordre",
  p:"Double validation humaine pour toute position de plus de deux unités. La salle de marché proteste : ça ralentit tout.",
  ch:[{b:"Accepter la double signature",s:"Le comité est rassuré, la salle râle.",e:{rc:6,lp:-1}},
      {b:"Refuser",s:"Le comité note votre refus au procès-verbal.",e:{rc:-5}}]},
 {who:"Table de volatilité",t:"Un client vous propose de lui vendre de la protection",
  p:"Une grande banque privée cherche un vendeur d'options de baisse sur les actions pour ses clients. La prime est généreuse.",
  ch:[{b:"Vendre la protection",s:"La prime rentre tout de suite ; le comité n'aime pas le risque de queue.",e:{cash:0.002,rc:-6}},
      {b:"Refuser",s:"Le comité approuve.",e:{rc:2}}]}
);
INCIDENTS.push(
 {t:"Double paiement d'un appel de marge",who:"Incident opérationnel",
  p:"Le back-office a payé deux fois le même appel de marge. Le remboursement prendra dix jours, et le prime broker facture l'avance.",
  loss:[0.0003,0.0015],lp:-2,rc:-5},
 {t:"Ordre de couverture passé dans le mauvais sens",who:"Incident opérationnel",
  p:"Au lieu de réduire l'exposition, l'ordre l'a doublée. Il a fallu une heure pour s'en apercevoir, et deux pour déboucler.",
  loss:[0.001,0.005],lp:-3,rc:-8},
 {t:"Panne électrique pendant la clôture",who:"Incident technique",
  p:"Le groupe électrogène n'a démarré qu'après douze minutes. Trois ordres de fin de séance sont restés en suspens.",
  loss:[0.0005,0.0025],lp:-2,rc:-6},
 {t:"Courriel d'un investisseur envoyé à tous les autres",who:"Incident de sécurité",
  p:"Un tableau de souscriptions, avec les noms et les montants, envoyé en copie à la liste de diffusion complète.",
  loss:[0.0001,0.0006],lp:-9,rc:-5},
 {t:"Erreur de change sur le collatéral",who:"Incident opérationnel",
  p:"Le collatéral en euros a été converti deux fois. La trésorerie a découvert le trou en fin de semaine.",
  loss:[0.0006,0.003],lp:-3,rc:-7},
 {t:"Un gérant a laissé une position ouverte sur son compte personnel",who:"Incident réglementaire",
  p:"Même marché, même sens, une semaine avant le fonds. Le régulateur parle de « coïncidence à expliquer ».",
  loss:[0.0005,0.003],lp:-6,rc:-10},
 {t:"Fournisseur de prix défaillant",who:"Incident technique",
  p:"Le flux de prix de clôture a servi les cours de la veille pendant deux jours. La valeur liquidative publiée était fausse.",
  loss:[0.0002,0.0012],lp:-7,rc:-6},
 {t:"Paramètre de risque effacé lors d'une mise à jour",who:"Incident technique",algoOnly:true,
  p:"Le plafond de taille par ordre a sauté pendant une mise à jour du moteur. Il a fallu deux heures pour s'en apercevoir.",
  loss:[0.001,0.005],lp:-3,rc:-9}
);
TAILEV.push(
 {t:"Le marché découvre la taille de votre position",who:"Prime broker · note confidentielle",sev:[0.45,0.75],
  p:"Un rapport réglementaire a rendu publiques les positions agrégées. Tout le monde sait où vous êtes, et combien il vous faut pour sortir.",
  o:["Tenir, les autres finiront par se lasser","Déboucler la moitié du book avant les autres","Acheter des options de couverture, au prix qu'on vous fait"]},
 {t:"Une contrepartie rappelle ses titres prêtés",who:"Desk · exécution",sev:[0.4,0.7],
  p:"Vos ventes à découvert reposaient sur des titres empruntés. Le prêteur les veut demain matin, et il n'y en a pas d'autres.",
  o:["Tenir et chercher un autre prêteur","Racheter la moitié du book dans le vide","Couvrir par des dérivés, au prix du vendeur"]},
 {t:"Gap d'ouverture après un week-end de crise",who:"Fil d'actualité · 06h40",sev:[0.5,0.8],
  p:"Un gouvernement est tombé samedi, une banque a fermé dimanche. Les marchés rouvrent lundi avec des écarts que personne n'a jamais vus.",
  o:["Attendre que les prix se stabilisent","Couper la moitié du book à l'ouverture","Acheter de la protection avant la cloche"]},
 {t:"Votre modèle de corrélation s'effondre",who:"Quantitatif · rapport",sev:[0.4,0.7],
  p:"Les marchés que vous teniez pour indépendants montent et baissent ensemble. Votre diversification n'existe plus depuis ce matin.",
  o:["Garder le book, la corrélation reviendra","Réduire le book de moitié tout de suite","Couvrir par un indice de volatilité"]},
 {t:"Votre plus gros investisseur rachète tout, maintenant",who:"Trésorerie · urgent",sev:[0.45,0.75],
  p:"Une clause oubliée lui permet de sortir sans préavis. Il faut trouver l'argent avant vendredi.",
  o:["Tenir et payer avec la trésorerie","Vendre la moitié du book pour payer","Emprunter contre le book, au taux du prime broker"]},
 {t:"Votre prime broker est dégradé de trois crans",who:"Juridique · alerte",sev:[0.4,0.7],
  p:"Vos marges et vos titres sont chez lui. Les autres clients retirent tout ; vous apprenez que la ségrégation des comptes « dépend de l'interprétation ».",
  o:["Rester et attendre la clarification","Transférer la moitié du book dans l'urgence","Couvrir le risque de contrepartie à n'importe quel prix"]}
);
'''
A="];\n\n/* ════════════════════ 4. ALÉA"
e.rep(A,"];\n"+NEW+"\n/* ════════════════════ 4. ALÉA")
e.done("lot 71")
