# Lot 121 : page d'accueil, page « Créez votre fonds » (règles, tutoriel, aides, styles, difficultés), tutoriels des jauges,
# du budget et des facteurs — alignés sur les mécaniques des lots 102–120.
import re
s=open('index.html',encoding='utf-8').read()
def rep(o,n,k=1):
    global s; c=s.count(o); assert c==k,(c,o[:90]); s=s.replace(o,n)
def sub1(pat,new):
    global s; m=list(re.finditer(pat,s,re.S)); assert len(m)==1,(len(m),pat[:60]); s=s[:m[0].start()]+new+s[m[0].end():]
# ── accueil
rep("<h1 class=\"splash-h1\">Vous prenez les commandes<br>d'un <em>fonds global macro</em></h1>","<h1 class=\"splash-h1\">Prenez les commandes<br>d'un <em>fonds global macro</em></h1>")
sub1(r'<p class="splash-p"><b style="color:var\(--gold\)">Le but : encaisser.*?la difficulté\.</p>',
 '<p class="splash-p">Ce matin, le conseil a remercié le CIO et vous a confié un fonds tout neuf. <b>Votre book.</b></p>\n'
 '  <p class="splash-p">Des rumeurs en pagaille, des positions à tenir dans la tempête, trois concurrents aux aguets qui n\'attendent que votre chute pour vous achever. Et surtout des investisseurs impatients quand ça monte, impitoyables quand ça baisse.</p>\n'
 '  <p class="splash-p">À vous de choisir votre style de gestion — et la difficulté. <b style="color:var(--gold)">Votre objectif : engranger un maximum de bonus avant de vous faire débarquer.</b></p>')
rep("Quatre fonds jouent le même trimestre que vous. Vos investisseurs comparent — et c'est l'écart à la médiane qui décide des rachats, pas votre performance absolue.",
    "Trois fonds jouent le même trimestre que vous, chacun dans son style. Vos investisseurs regardent le classement : le fonds de fonds vous juge sur la moyenne des concurrents.")
# ── création du fonds
rep("<div class=\"sub\">cinq choix, puis le premier trimestre</div>","<div class=\"sub\">trois choix, puis le premier trimestre</div>")
rep("<button class=\"cta ghost\" id=\"howto\" style=\"margin-top:12px\">Comment on joue, comment on gagne</button>",
    "<button class=\"cta ghost\" id=\"howto\" style=\"margin-top:12px\"><span class=\"hintq big\">?</span> Comment on joue</button>")
sub1(r' <div class="prose" id="introprose" style="display:none">.*?</div>\n <details class="wire" style="margin-top:16px"><summary>Comment on gagne, comment on perd, ce que ça coûte</summary>\n <div class="rules" style="margin-top:0">.*?</div></details>',
 ''' <div class="prose" id="introprose" style="display:none">
  <p><b>Chaque trimestre, quatre temps.</b> Le <b>budget</b> : l'équipe que vous payez. Le <b>book</b> : vos positions, à l'achat ou à la vente, sur jusqu'à 25 marchés. L'<b>annonce</b> : ce que vous promettez aux investisseurs. Puis trois mois de <b>dépêches</b> : suivre le mouvement, ou ne pas bouger.</p>
  <p><b>Votre score, c'est votre trésorerie</b> : commissions de gestion et de performance, moins l'équipe, les ordres et les bonus. Une seule clôture dans le rouge, et votre société dépose le bilan.</p>
  <p>Tout le jeu tient dans cette tension : prendre assez de risque pour gagner, pas assez pour sauter.</p>
 </div>
 <details class="wire" style="margin-top:16px"><summary>Les règles en cinq lignes</summary>
 <div class="rules" style="margin-top:0">
  <div class="rule"><b>Gagner</b><span>Accumuler de la trésorerie jusqu'au bout du mandat.</span></div>
  <div class="rule"><b>Perdre</b><span>Une clôture en trésorerie négative, ou un fonds vidé par les rachats.</span></div>
  <div class="rule"><b>Frais</b><span id="feeline">${feeLine()}</span></div>
  <div class="rule"><b>Investisseurs</b><span>Chacun son critère : la régularité, l'objectif annoncé, la performance absolue, la moyenne des concurrents. La confiance décide du montant de leurs rachats et de leurs souscriptions.</span></div>
  <div class="rule"><b>Comité</b><span>Trois limites affichées sur le book : risque ex ante, concentration, stop trimestriel. Les franchir coûte un carton ; deux jaunes font un rouge, et un rouge impose des contraintes.</span></div>
  <div class="rule"><b>Chocs</b><span>Le prime broker vérifie la marge après chaque événement. Des événements extrêmes peuvent frapper chaque trimestre ; une rumeur, ou le pouvoir de votre style, les annonce parfois.</span></div>
  <div class="rule"><b>Le piège</b><span>Vingt-cinq marchés, quatre forces derrière eux : croissance, inflation, liquidité, appétit pour le risque. Un book qui semble diversifié peut n'être qu'un seul pari.</span></div>
 </div></details>''')
rep("return `Votre mandat facture <strong>2 % de gestion</strong> et <strong>${(z.perf*100).toFixed(0)} % de la performance</strong> au-dessus du plus haut historique, plus le budget d'exploitation que vous fixez chaque trimestre. Objectif : <strong>12 % net par an</strong>.`;",
    "return `Le fonds vous verse <strong>2 % de gestion</strong> par an et <strong>${(z.perf*100).toFixed(0)} % de sa performance</strong> au-dessus de son plus haut historique. Votre société paie l'équipe, les ordres et les bonus.`;")
rep("r<sub>i</sub> = σ<sub>i</sub>(Σ<sub>k</sub> b<sub>ik</sub>f<sub>k</sub> + e<sub>i</sub>z<sub>i</sub>)","r<sub>i</sub> = σ<sub>i</sub>(Σ<sub>k</sub> b<sub>ik</sub>f<sub>k</sub> + e<sub>i</sub>z<sub>i</sub>) — croissance, inflation, liquidité (l'inverse du dollar), appétit pour le risque")
rep("g.textContent=ok?\"Prendre le book\":\"Choisissez vos cinq options\";","g.textContent=ok?\"Prendre le book\":\"Choisissez vos trois options\";")
# aides : points d'interrogation dorés
rep(".hintq{display:inline-flex;align-items:center;justify-content:center;width:17px;height:17px;margin-left:6px;\n border-radius:50%;border:1px solid var(--gold);background:transparent;color:var(--gold);\n font-size:11px;font-weight:600;line-height:1;vertical-align:middle;flex-shrink:0}",
    ".hintq{display:inline-flex;align-items:center;justify-content:center;width:20px;height:20px;margin-left:7px;\n border-radius:50%;border:1px solid var(--gold);background:var(--gold);color:#1a1405;\n font-size:12.5px;font-weight:800;line-height:1;vertical-align:middle;flex-shrink:0;cursor:pointer}\n.hintq.big{width:22px;height:22px;margin:0 8px 0 0;font-size:14px}")
rep(" prof:\"Votre style décide du poids accordé aux rumeurs que vous achetez face aux signaux de marché — tendance, portage, valeur. Le systématique suit les signaux et se passe de conviction ; le fondamental mise sur l'information et paie pour l'avoir.\",",
    " prof:\"Votre style décide de ce que votre desk lit le mieux (les sources, les signaux de marché, ou le flux), de son pouvoir propre et de la patience de vos investisseurs. Le quantitatif est le plus sûr, le fondamental le plus informé, le flux le plus rapide et le plus exposé.\",")
rep(" size:\"Tout le monde part avec 100 M$, sans mandat de volatilité. La difficulté règle l'adresse des trois concurrents, la vigilance du comité, la voracité des investisseurs et la nervosité de leurs flux — et la commission de performance que vous touchez : 15, 20 ou 30 %.\",",
    " size:\"Tout le monde part avec un fonds de 100 M$. La difficulté règle l'adresse des trois concurrents, la nervosité de vos investisseurs, le prix de votre équipe, le capital de départ de votre société — et la part de la performance que vous touchez : 15, 20 ou 30 %.\",")
# styles
rep("p:\"Vous ne formez pas d'opinion, vous estimez des paramètres. Les sources deviennent un vecteur de vraisemblance, les signaux une matrice de covariance, et la décision tombe d'un programme d'optimisation que personne dans la salle ne relit plus depuis trois ans. Vous ne savez pas pourquoi le book est long du yen. Le modèle, lui, le sait.\",\n  ef:[",
    "p:\"Pas d'opinion : un modèle. Il lit tous les signaux, pèse toutes les sources et vous propose un book d'un bouton. Vous ne savez pas toujours pourquoi il est long du yen. Lui, si.\",\n  ef:[")
rep("ef:[['g',\"<b>Pouvoir propre — le book du modèle</b> : un portefeuille optimisé sur toutes les sources et tous les signaux, pondérés par leur vraisemblance, appliqué d'un bouton\"],['g',\"rapports réguliers : jauge investisseurs 25 % moins nerveuse\"],['g',\"des investisseurs qui connaissent la stratégie : rachats pour repli à partir de 40 % de perte au lieu de 28 %\"],['b',\"le modèle ne vise que 18 % de vol : régulier, mais il laisse du rendement\"],",
    "ef:[['g',\"<b>Pouvoir propre — le book du modèle</b> : un portefeuille optimisé sur toutes les sources et tous les signaux, appliqué d'un bouton ; le modèle de risque annonce parfois l'événement extrême et chiffre sa perte\"],['g',\"il lit tendance, portage et valeur plus nettement que les autres styles\"],['g',\"investisseurs 25 % moins nerveux\"],['g',\"clause de repli de la caisse de retraite à 40 % de perte au lieu de 28 %\"],['b',\"le modèle vise 18 % de vol : régulier, mais il laisse du rendement\"],")
rep("p:\"Vous construisez une vue du monde, ligne par ligne, et vous la défendez contre le marché, contre le comité, contre vos propres analystes. Vous avez passé trois nuits sur la balance courante d'un pays que personne ne regarde. Vous aurez raison. La seule question est de savoir si votre mandat vous survivra jusque-là.\",",
    "p:\"Une vue du monde, construite ligne par ligne, et défendue contre tous. Vous avez passé trois nuits sur la balance courante d'un pays que personne ne regarde. Vous aurez raison — reste à savoir si votre mandat tiendra jusque-là.\",")
rep("ef:[['g',\"<b>Pouvoir propre — la source vérifiée</b> : chaque trimestre, deux rumeurs sont recoupées par votre réseau et vous sont données pour certaines\"],",
    "ef:[['g',\"<b>Pouvoir propre — la source vérifiée</b> : chaque trimestre, deux rumeurs sont recoupées et données pour certaines ; une fois sur deux, votre réseau vous nomme l'événement extrême qui arrive\"],")
rep("p:\"Vous ne prédisez rien. Vous écoutez. Le marché parle en permanence et la plupart des gens sont trop occupés à avoir des opinions pour l'entendre. Vous regardez un carnet d'ordres comme d'autres regardent la mer. Vos analystes ont renoncé à vous demander vos raisons ; votre comité a renoncé à les consigner. Il vous arrive d'avoir raison avant d'avoir compris pourquoi.\",",
    "p:\"Vous ne prédisez rien : vous écoutez le marché. Vous regardez un carnet d'ordres comme d'autres regardent la mer, et il vous arrive d'avoir raison avant d'avoir compris pourquoi.\",")
rep("ef:[['g',\"<b>Pouvoir propre — l'intuition</b> : chaque trimestre, un facteur macro vous souffle le sens de sa réalisation avant tout le monde, et elle ne se trompe qu'environ une fois sur cinq. Ne demandez pas comment\"],",
    "ef:[['g',\"<b>Pouvoir propre — l'intuition</b> : chaque trimestre, le sens d'un facteur macro avant tout le monde, juste quatre fois sur cinq ; et vous sentez toujours venir un événement extrême, sans savoir lequel\"],")
rep("['b',\"de l'argent rapide : rachats pour repli dès 22 % de perte au lieu de 28 %\"]","['b',\"clause de repli de la caisse de retraite dès 22 % de perte au lieu de 28 %\"]")
rep("['b',\"aucune source supplémentaire : vous n'en demandez pas\"]]","['b',\"aucune source supplémentaire : vous n'en demandez pas\"],['b',\"aucun capital de départ supplémentaire\"]]")
# difficultés
rep("p:\"Des concurrents solides mais battables, un comité qui vous laisse respirer, des investisseurs qui pardonnent un mauvais trimestre. Vous touchez 15 % de la performance au-dessus du plus haut historique.\",\n  ef:[[\"g\",\"capital de départ de la société de gestion : 0,45 M$ (plus le bonus de votre style) ; équipe 15 % moins chère\"],[\"g\",\"concurrents moins adroits\"],[\"g\",\"investisseurs patients, flux plus calmes\"],[\"g\",\"comité indulgent\"],[\"b\",\"commission de performance : 15 %\"]],",
    "p:\"Des concurrents battables, des investisseurs qui pardonnent un mauvais trimestre, une équipe bon marché. Vous touchez 15 % de la performance.\",\n  ef:[[\"g\",\"capital de départ : 0,45 M$, plus celui de votre style\"],[\"g\",\"équipe 15 % moins chère\"],[\"g\",\"concurrents moins adroits\"],[\"g\",\"investisseurs patients : confiance de départ +8, rachats 25 % plus petits\"],[\"b\",\"commission de performance : 15 %\"],[\"b\",\"souscriptions 40 % plus petites\"]],")
rep("p:\"Trois très bons concurrents, un comité vigilant, des investisseurs qui comparent. La commission de performance habituelle du métier : 20 %.\",\n  ef:[[\"g\",\"commission de performance : 20 %\"],[\"g\",\"capital de départ de la société de gestion : 0,15 M$ (plus le bonus de votre style)\"],[\"b\",\"concurrents très bons, chacun dans son style\"],[\"b\",\"investisseurs exigeants, comité vigilant\"]],",
    "p:\"Trois très bons concurrents, des investisseurs qui comparent, le tarif habituel du métier : 20 % de la performance.\",\n  ef:[[\"g\",\"commission de performance : 20 %\"],[\"g\",\"capital de départ : 0,15 M$, plus celui de votre style\"],[\"b\",\"concurrents très bons, chacun dans son style\"],[\"b\",\"investisseurs exigeants\"]],")
rep("p:\"Des concurrents au sommet de leur art, un comité sur votre dos, des investisseurs voraces dont l'argent part aussi vite qu'il arrive. En échange, vous touchez 30 % de la performance, et les souscriptions arrivent aussi vite que les rachats.\",\n  ef:[[\"g\",\"commission de performance : 30 %\"],[\"b\",\"pas de capital de départ au-delà du bonus de votre style ; équipe 35 % plus chère\"],[\"g\",\"flux violents dans les deux sens : un bon trimestre attire gros\"],[\"b\",\"concurrents au sommet de leur art\"],[\"b\",\"investisseurs voraces, flux violents\"],[\"b\",\"comité impitoyable\"]],",
    "p:\"Des concurrents au sommet de leur art, des investisseurs voraces, une équipe hors de prix. En échange : 30 % de la performance, et l'argent arrive aussi vite qu'il part.\",\n  ef:[[\"g\",\"commission de performance : 30 %\"],[\"g\",\"souscriptions 60 % plus grosses : un bon trimestre attire gros\"],[\"b\",\"aucun capital de départ, sauf celui de votre style\"],[\"b\",\"équipe 35 % plus chère\"],[\"b\",\"concurrents au sommet de leur art\"],[\"b\",\"investisseurs voraces : confiance de départ −8, pertes 40 % plus mal vécues, rachats 15 % plus gros\"]],")
# tutoriels
rep("<p>Tout le jeu se lit dans cette barre. La <b>confiance</b> résume deux jugements : celui des investisseurs, qui regardent la performance, et celui du comité des risques, qui regarde la discipline. Sous 20, l'un comme l'autre fait partir de l'argent par des rachats. La partie ne s'arrête que si l'encours tombe sous 5 % de son niveau de départ.</p>",
    "<p>Tout le jeu se lit dans cette barre. La <b>confiance</b> de vos investisseurs décide de la taille de leurs rachats et de leurs souscriptions ; leur critère décide du moment. Le <b>carton</b> à droite rappelle où vous en êtes avec le comité des risques.</p>")
rep("<b>Trésorerie</b>, c'est votre score : les commissions encaissées, moins ce que vous dépensez. Un dixième de la trésorerie d'ouverture est investi dans le fonds et en suit les gains comme les pertes. Chaque jauge s'ouvre d'un clic et explique son propre calcul.</p>",
    "<b>Trésorerie</b>, c'est votre score : les commissions encaissées, moins ce que vous dépensez. Une clôture dans le rouge, et c'est le dépôt de bilan. Chaque jauge s'ouvre d'un clic et explique son propre calcul.</p>")
rep("Votre société n'a pas de capital : sa trésorerie, ce sont vos gains nets.","Votre société part avec un petit capital, qui dépend de la difficulté et de votre style ; ensuite, sa trésorerie, ce sont vos gains nets.")
rep("En début de partie, la caisse se limite à la première commission de gestion : gardez des budgets serrés, vous les relèverez quand les commissions de performance rentreront.</p>",
    "En début de partie, gardez une réserve pour les ordres : une seule clôture en trésorerie négative, et la société dépose le bilan. Vous relèverez l'équipe quand les commissions de performance rentreront.</p>")
rep("<b>C</b>roissance, <b>I</b>nflation, <b>D</b>ollar, <b>A</b>ppétit pour le risque.","<b>C</b>roissance, <b>I</b>nflation, <b>L</b>iquidité, <b>A</b>ppétit pour le risque.")
open('index.html','w',encoding='utf-8').write(s);print('lot121 p1 ok')
