# Lot 142 : fin de partie — trois variantes par verdict, tirées de façon déterministe (graine et trimestre).
s=open('index.html',encoding='utf-8').read()
def rep(o,n,k=1):
    global s; c=s.count(o); assert c==k,(c,o[:90]); s=s.replace(o,n)
rep(" let verdict,vtxt;const ANS="," const vp=a=>a[((S.seed>>>0)+S.q*7)%a.length];   /* lot 142 */\n let verdict,vtxt;const ANS=")
rep("vtxt=S.over==='cash'?`Trésorerie négative à la clôture du trimestre ${S.q} : les commissions ne paient plus l'équipe, le loyer et les ordres. La société de gestion dépose le bilan ; le conseil confie le fonds à une autre maison.`",
    "vtxt=S.over==='cash'?vp([`Trésorerie négative à la clôture du trimestre ${S.q} : les commissions ne paient plus l'équipe, le loyer et les ordres. La société de gestion dépose le bilan ; le conseil confie le fonds à une autre maison.`,`Trimestre ${S.q} : le banquier de la société de gestion a refusé le découvert. Josiane éteint les écrans, Gontran fait l'inventaire, et le fonds part chez un concurrent.`,`Au trimestre ${S.q}, la caisse est vide. Le conseil vous remercie pour votre « énergie » et nomme un administrateur provisoire.`])")
rep("else if(cagr>0.25&&rank===1){verdict=\"Une signature sur la place\";vtxt=`${ANS} de mandat, et vous finissez devant les trois. Les allocataires font la queue, le fonds ferme aux souscriptions : désormais, c'est vous qui choisissez vos clients.`}",
    "else if(cagr>0.25&&rank===1){verdict=\"Une signature sur la place\";vtxt=vp([`${ANS} de mandat, et vous finissez devant les trois. Les allocataires font la queue, le fonds ferme aux souscriptions : désormais, c'est vous qui choisissez vos clients.`,`${ANS} et la première place. Un magazine vous met en couverture ; vos concurrents encadrent la page, pour s'en souvenir.`,`Devant les trois, ${ANS} durant. Le conseil vous propose une part de la société de gestion. Votre stagiaire vous demande un autographe.`])}")
rep("else if(cagr>0.18&&S.maxdd<0.20){verdict=`${ANSC} de référence`;vtxt=\"Performance et discipline de risque : le genre de courbe qu'on imprime dans les présentations. Le conseil vous propose d'ouvrir un second fonds.\"}",
    "else if(cagr>0.18&&S.maxdd<0.20){verdict=`${ANSC} de référence`;vtxt=vp([\"Performance et discipline de risque : le genre de courbe qu'on imprime dans les présentations. Le conseil vous propose d'ouvrir un second fonds.\",\"Une courbe régulière, sans trou. Mireille Cauchemar l'a fait encadrer pour le bureau du comité.\",\"Bon rendement, petit repli : les consultants vous classent dans le premier décile, et le disent.\"])}")
rep("else if(cagr>0.12){verdict=\"Mandat renouvelé, avec les honneurs\";vtxt=`Vous tenez l'objectif, et plus. Les investisseurs resignent pour ${ANS} de plus et augmentent leurs tickets.`}",
    "else if(cagr>0.12){verdict=\"Mandat renouvelé, avec les honneurs\";vtxt=vp([`Vous tenez l'objectif, et plus. Les investisseurs resignent pour ${ANS} de plus et augmentent leurs tickets.`,`Objectif dépassé. La caisse des Cheminots double sa ligne, Nordhavn vous invite au fjord.`,`Le mandat est renouvelé sans débat. Le conseil passe directement au point suivant, ce qui est le plus beau des compliments.`])}")
rep("else if(cagr>0.03){verdict=\"Vous survivez\";vtxt=\"Assez pour continuer, pas assez pour lever. Le fonds reste sous-dimensionné pour ses ambitions.\"}",
    "else if(cagr>0.03){verdict=\"Vous survivez\";vtxt=vp([\"Assez pour continuer, pas assez pour lever. Le fonds reste sous-dimensionné pour ses ambitions.\",\"Le mandat continue, sans fanfare. Le family office Vandermeer vous demande « un peu plus de panache ».\",\"Vous êtes encore là, ce qui n'est pas le cas de tout le monde. On vous accorde un trimestre de patience de plus, puis on verra.\"])}")
rep("else if(cagr>-0.05){verdict=`${ANSC} pour rien`;vtxt=\"Frais payés, risque pris, rien produit. Les allocataires appellent ça un coût d'option.\"}",
    "else if(cagr>-0.05){verdict=`${ANSC} pour rien`;vtxt=vp([\"Frais payés, risque pris, rien produit. Les allocataires appellent ça un coût d'option.\",\"Beaucoup de travail, un résultat plat. Le fonds de fonds Albatros vous a déjà rangé dans la colonne « à revoir ».\",\"Le fonds n'a ni gagné ni perdu. Votre équipe, elle, a gagné ses bonus. Les investisseurs l'ont remarqué.\"])}")
rep("else{verdict=\"Sous l'eau\";vtxt=\"Le plus haut historique est loin au-dessus. Vous travaillerez sans commission de performance jusqu'à le retrouver.\"}",
    "else{verdict=\"Sous l'eau\";vtxt=vp([\"Le plus haut historique est loin au-dessus. Vous travaillerez sans commission de performance jusqu'à le retrouver.\",\"Le fonds a perdu de l'argent, et le conseil vous garde : il serait trop cher de vous remplacer. Ce n'est pas un compliment.\",\"Sous l'eau, et loin du bord. Les investisseurs qui restent sont ceux qui ne peuvent pas partir.\"])}")
open('index.html','w',encoding='utf-8').write(s);print('lot142 p1 ok')
