p='index.html';s=open(p,encoding='utf-8').read()
def rep(o,n,k=1):
    global s;c=s.count(o);assert c==k,(o[:60],c);s=s.replace(o,n)
# lot 284 : progression de difficulté — quant < fondamental < chasseur de queues < valeur relative < flux < activiste
rep("sigBonus:0,capture:0.50,tcMult:0.72,rumBonus:0.05,lpMult:0.75,","sigBonus:0,capture:0.50,tcMult:0.85,rumBonus:0.05,lpMult:0.85,")
rep("sigBonus:5,capture:0.60,tcMult:1.15,rumBonus:0.18,lpMult:1.0,incMult:1.35,incSev:1.4,","sigBonus:5,capture:0.60,tcMult:1.0,rumBonus:0.18,lpMult:1.0,incMult:1.35,incSev:1.2,")
rep("incMult:1.70,incSev:2.8,numeric:false,freeAdj:true,hunch:true}","incMult:1.70,incSev:2.2,numeric:false,freeAdj:true,hunch:true}")
rep("sigBonus:0,capture:0.55,tcMult:0.80,","sigBonus:0,capture:0.55,tcMult:0.70,")
rep("sigBonus:2,capture:0.75,tcMult:1.20,","sigBonus:2,capture:0.75,tcMult:1.30,")
rep("const STYCOST={syst:0.85,fonda:1,flux:1.35,rv:1.10,tail:0.90,act:1.20};","const STYCOST={syst:0.95,fonda:0.95,flux:1.20,rv:1.0,tail:0.90,act:1.20};")
rep("*(S&&S.prof==='rv'?2:1)}   /* lot 270 : les paires divergent */","*(S&&S.prof==='rv'?1.5:1)}   /* lot 270 : les paires divergent ; lot 284 : ×1,5 */")
rep("const PAIRA=0.30;","const PAIRA=0.40;   /* lot 284 : 0,30 → 0,40 */")
rep("const ATK={stake:0.05,win:1.2,p0:0.25,","const ATK={stake:0.05,win:1.2,p0:0.20,")
open(p,'w',encoding='utf-8').write(s)
s=open(p,encoding='utf-8').read()
def R(o,n,k=1):
    global s;c=s.count(o);assert c==k,(o[:50],c);s=s.replace(o,n)
R("coûts d'exécution −28 %","coûts d'exécution −15 %")
R("investisseurs 25 % moins nerveux","investisseurs 15 % moins nerveux",2)
R("capital de départ +0,5 M$ ; équipe 15 % moins chère","capital de départ +0,5 M$ ; équipe 5 % moins chère")
R("coûts de transaction −28 % : le modèle exécute sans état d'âme","coûts de transaction −15 % : le modèle exécute sans état d'âme")
R(" ; coûts de transaction +15 % : vous arbitrez tard ;"," ; équipe 5 % moins chère ;")
R("coûts +15 %, incidents plus fréquents et plus chers","incidents plus fréquents et plus chers")
R("plus chers (×1,4)","plus chers (×1,2)")
R("presque trois fois plus chers","plus de deux fois plus chers",2)
R("équipe 35 % plus chère","équipe 20 % plus chère",2)
R("coûts d'exécution −20 %","coûts d'exécution −30 %")
R("coûts de transaction −20 %","coûts de transaction −30 %")
R("décote de liquidité ×2","décote de liquidité ×1,5")
R("décote de liquidité doublée","décote de liquidité ×1,5")
R(",['b',\"équipe 10 % plus chère : il faut des docteurs en mathématiques\"]","")
R("coûts d'exécution +20 %","coûts d'exécution +30 %")
R("coûts de transaction +20 %","coûts de transaction +30 %")
R("35 à 55 %","30 à 50 %")
open(p,'w',encoding='utf-8').write(s)
s=open(p,encoding='utf-8').read()
R("lvl:'Expert',who:\"« Je ne parie pas sur le marché, je parie sur l'écart »\"","lvl:'Normal',who:\"« Je ne parie pas sur le marché, je parie sur l'écart »\"")
open(p,'w',encoding='utf-8').write(s)
