# Lot 141 : six anecdotes de milieu de trimestre (TRADER_MID), toute l'équipe.
s=open('index.html',encoding='utf-8').read()
def rep(o,n,k=1):
    global s; c=s.count(o); assert c==k,(c,o[:90]); s=s.replace(o,n)
NEW=r'''
 {"who": "Ingrid Bergström · taux", "t": "« Le Bund vient de bouger de vingt points de base en dix minutes. Je ne touche à rien »", "p": "Elle boit son thé. Elle ne regarde même pas l'écran. « Quand ça bouge comme ça, c'est que quelqu'un se trompe. »", "ch": [{"b": "La laisser attendre", "s": "50 % de ±0,15 % sur le trimestre.", "e": {"risk": [0.5, 0.0015], "riskMsg": "Elle avait raison : le Bund est revenu", "safeTxt": "Il n'est pas revenu. Ingrid repose sa tasse : −0,15 %.", "safePnl": -0.0015}}, {"b": "Couper tout de suite", "s": "Coûts +10 % ce trimestre.", "e": {"tcMult": 1.1}}]},
 {"who": "Dwight Tannenbaum · actions, à la voix", "t": "« Mon téléphone fixe ne marche plus. Il me reste trois portables et un fax »", "p": "Il tape sur le combiné comme sur une télévision des années 80.", "ch": [{"b": "Faire venir le technicien en urgence", "s": "−1 pb.", "e": {"cash": -0.0001}}, {"b": "Laisser Dwight se débrouiller", "s": "Coûts +5 % ce trimestre sur les actions.", "e": {"tcMult": 1.05}}]},
 {"who": "Bartolomeo « Tuco » Ossobuco · énergie", "t": "« Mon cousin de Rotterdam dit qu'un pétrolier fait demi-tour. Je ne sais pas pourquoi »", "p": "« Un cousin ne dit jamais pourquoi. Il dit juste demi-tour. »", "ch": [{"b": "Croire le cousin", "s": "40 % de chances de +0,2 %, sinon −0,1 %.", "e": {"risk": [0.6, -0.001], "riskMsg": "Le pétrolier avait juste oublié un marin", "safeTxt": "Le pétrolier a fait demi-tour pour de bon : +0,2 %.", "safePnl": 0.002}}, {"b": "Ignorer le cousin", "s": "Rien. Tuco est vexé (débauchage +5 %).", "e": {"poach": 0.05}}]},
 {"who": "Wing-Fat « Winnie » Leung · Asie", "t": "« Je suis à Hong Kong pour un mariage. Je trade depuis la salle de bal »", "p": "On entend un orchestre. Puis des applaudissements. Puis « achète ».", "ch": [{"b": "La laisser trader au mariage", "s": "Coûts −10 % ce trimestre sur les exotiques, comité −1.", "e": {"tcMult": 0.9, "rc": -1}}, {"b": "Lui dire de profiter du mariage", "s": "Coûts +5 % ce trimestre. Winnie danse.", "e": {"tcMult": 1.05}}]},
 {"who": "Sœur Marie-Alpha · exécution systématique", "t": "« Le modèle a détecté un régime nouveau. Je propose un jeûne de trois jours pour le recalibrer »", "p": "« Le jeûne, c'est pour moi. Le modèle, je le relance ce soir. »", "ch": [{"b": "Recalibrer tout de suite", "s": "−2 pb de calcul, comité +1.", "e": {"cash": -0.0002, "rc": 1}}, {"b": "Attendre la fin du trimestre", "s": "25 % de risque d'un mauvais signal : −0,15 %.", "e": {"risk": [0.25, -0.0015], "riskMsg": "Le régime avait bien changé, le modèle non"}}]},
 {"who": "Le professeur Atterrissage · économiste en chef", "t": "« J'ai prévu la récession sur une chaîne et la reprise sur une autre. Le même jour »", "p": "« Les deux étaient en direct. Les deux étaient sincères. »", "ch": [{"b": "Lui demander de choisir", "s": "Comité +1, le professeur boude (débauchage +5 %).", "e": {"rc": 1, "poach": 0.05}}, {"b": "S'en servir comme publicité", "s": "Confiance +1, comité −1.", "e": {"lp": 1, "rc": -1}}]},'''
rep("const TRADER_MID=[","const TRADER_MID=["+NEW)
open('index.html','w',encoding='utf-8').write(s);print('lot141 p1 ok')
